package reporter

import (
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/cozygarage/sentinelflow/pkg/api"
)

// MarkdownFormatter formats reports as Markdown for GitHub/GitLab PR comments
type MarkdownFormatter struct{}

func (f *MarkdownFormatter) Format(result *api.ScanResult) (string, error) {
	var md strings.Builder

	// Header
	md.WriteString("# 🛡️ SentinelFlow Security Scan Report\n\n")

	// Summary table
	counts := result.CountBySeverity()
	totalFindings := len(result.Findings)

	md.WriteString("## 📊 Summary\n\n")
	md.WriteString("| Metric | Value |\n")
	md.WriteString("|--------|-------|\n")
	md.WriteString(fmt.Sprintf("| **Target** | `%s` |\n", escapeMarkdownInline(result.Metadata.TargetPath)))
	md.WriteString(fmt.Sprintf("| **Scan Duration** | %s |\n", result.Duration.Std().Round(time.Millisecond)))
	md.WriteString(fmt.Sprintf("| **Scanners Run** | %d |\n", len(result.ScannerRuns)))
	md.WriteString(fmt.Sprintf("| **Total Findings** | **%d** |\n", totalFindings))
	if result.Baseline != nil && result.Baseline.Enabled {
		md.WriteString(fmt.Sprintf("| **Baselined (suppressed)** | %d |\n", result.Baseline.Suppressed))
		md.WriteString(fmt.Sprintf("| **New findings** | **%d** |\n", result.Baseline.New))
	}
	md.WriteString("\n")

	// Severity badges
	md.WriteString("### Findings by Severity\n\n")
	if counts[api.SeverityCritical] > 0 {
		md.WriteString(fmt.Sprintf("🔴 **Critical**: %d  \n", counts[api.SeverityCritical]))
	}
	if counts[api.SeverityHigh] > 0 {
		md.WriteString(fmt.Sprintf("🟠 **High**: %d  \n", counts[api.SeverityHigh]))
	}
	if counts[api.SeverityMedium] > 0 {
		md.WriteString(fmt.Sprintf("🟡 **Medium**: %d  \n", counts[api.SeverityMedium]))
	}
	if counts[api.SeverityLow] > 0 {
		md.WriteString(fmt.Sprintf("🔵 **Low**: %d  \n", counts[api.SeverityLow]))
	}
	if counts[api.SeverityInfo] > 0 {
		md.WriteString(fmt.Sprintf("⚪ **Info**: %d  \n", counts[api.SeverityInfo]))
	}
	md.WriteString("\n")

	// Scanner results
	md.WriteString("## 🔍 Scanner Results\n\n")
	md.WriteString("| Scanner | Status | Findings | Duration |\n")
	md.WriteString("|---------|--------|----------|----------|\n")

	for _, run := range result.ScannerRuns {
		status := "✅"
		if run.Error != "" {
			status = "❌"
		}
		md.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n",
			escapeMarkdownCell(run.Scanner), status, run.FindingsCount, run.Duration.Std().Round(time.Millisecond)))
	}
	md.WriteString("\n")

	// Detailed findings
	if totalFindings > 0 {
		md.WriteString("## 📋 Detailed Findings\n\n")

		// Group by severity
		for _, severity := range []api.Severity{
			api.SeverityCritical,
			api.SeverityHigh,
			api.SeverityMedium,
			api.SeverityLow,
		} {
			findings := result.FilterBySeverity(severity)
			if len(findings) == 0 {
				continue
			}

			icon := f.getSeverityIcon(severity)
			md.WriteString(fmt.Sprintf("### %s %s Severity (%d)\n\n", icon, capitalize(string(severity)), len(findings)))

			for i, finding := range findings {
				if i >= 10 && len(findings) > 10 {
					md.WriteString(fmt.Sprintf("\n*...and %d more %s findings*\n\n", len(findings)-10, severity))
					break
				}

				md.WriteString("<details>\n")
				md.WriteString(fmt.Sprintf("<summary><strong>%s</strong> - %s</summary>\n\n",
					html.EscapeString(finding.RuleID), html.EscapeString(finding.Title)))
				md.WriteString(fmt.Sprintf("**File:** `%s:%d`\n\n",
					escapeMarkdownInline(finding.Location.File), finding.Location.StartLine))
				md.WriteString(fmt.Sprintf("**Description:** %s\n\n", escapeMarkdownText(finding.Description)))

				if finding.CVE != "" {
					cve := escapeMarkdownInline(finding.CVE)
					md.WriteString(fmt.Sprintf("**CVE:** [%s](https://nvd.nist.gov/vuln/detail/%s)\n\n", cve, cve))
				}

				if finding.CVSS > 0 {
					md.WriteString(fmt.Sprintf("**CVSS Score:** %.1f\n\n", finding.CVSS))
				}

				if finding.Remediation != "" {
					md.WriteString(fmt.Sprintf("**Remediation:** %s\n\n", escapeMarkdownText(finding.Remediation)))
				}

				if len(finding.References) > 0 {
					md.WriteString("**References:**\n")
					for _, ref := range finding.References {
						md.WriteString(fmt.Sprintf("- %s\n", escapeMarkdownText(ref)))
					}
					md.WriteString("\n")
				}

				if finding.Location.Snippet != "" {
					md.WriteString("**Code Snippet:**\n```\n")
					md.WriteString(sanitizeCodeFence(finding.Location.Snippet))
					md.WriteString("\n```\n\n")
				}

				md.WriteString("</details>\n\n")
			}
		}
	} else {
		md.WriteString("## ✅ No Security Issues Found!\n\n")
		md.WriteString("Great job! The scan did not detect any security vulnerabilities.\n\n")
	}

	// Footer
	md.WriteString("---\n")
	md.WriteString(fmt.Sprintf("*Generated by SentinelFlow %s at %s*\n",
		escapeMarkdownInline(result.Metadata.SentinelFlowVersion),
		result.Metadata.EndTime.Format("2006-01-02 15:04:05")))

	return md.String(), nil
}

func escapeMarkdownCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return html.EscapeString(s)
}

func escapeMarkdownInline(s string) string {
	s = strings.ReplaceAll(s, "`", "'")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func escapeMarkdownText(s string) string {
	replacer := strings.NewReplacer(
		"<", "&lt;",
		">", "&gt;",
		"[", "\\[",
		"]", "\\]",
		"|", "\\|",
	)
	return replacer.Replace(s)
}

func sanitizeCodeFence(s string) string {
	// Prevent breaking out of fenced code blocks in PR comments
	return strings.ReplaceAll(s, "```", "'''")
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func (f *MarkdownFormatter) getSeverityIcon(severity api.Severity) string {
	switch severity {
	case api.SeverityCritical:
		return "🔴"
	case api.SeverityHigh:
		return "🟠"
	case api.SeverityMedium:
		return "🟡"
	case api.SeverityLow:
		return "🔵"
	case api.SeverityInfo:
		return "⚪"
	default:
		return "⚫"
	}
}
