package quality

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/cozygarage/sentinelflow/internal/config"
	"github.com/cozygarage/sentinelflow/internal/scanner/sast"
	"github.com/cozygarage/sentinelflow/internal/scanner/secrets"
	"github.com/cozygarage/sentinelflow/pkg/api"
)

type labelsFile struct {
	Findings []struct {
		Scanner string `yaml:"scanner"`
		Rule    string `yaml:"rule"`
		File    string `yaml:"file"`
		Expect  bool   `yaml:"expect"`
	} `yaml:"findings"`
}

func corpusRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("caller")
	}
	root := filepath.Join(filepath.Dir(file), "..", "..", "testdata", "corpus")
	root, err := filepath.Abs(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(root); err != nil {
		t.Fatalf("corpus missing: %s", root)
	}
	return root
}

func TestLabeledCorpusPrecisionRecall(t *testing.T) {
	root := corpusRoot(t)
	// Assemble AWS-shaped keys at runtime so the committed fixture never
	// contains a contiguous Access Key ID (GitHub push protection).
	leaked := filepath.Join(root, "secrets", "leaked.env")
	k1 := "AKIA" + "TESTKEY000000001"
	k2 := "AKIA" + "TESTKEY000000002"
	if err := os.WriteFile(leaked, []byte("AWS_ACCESS_KEY_ID="+k1+"\nAWS_ACCESS_KEY_ID_2="+k2+"\n"), 0644); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.WriteFile(leaked, []byte("# regenerated by corpus test\nSENTINELFLOW_CORPUS_AWS=1\n"), 0644)
	})

	raw, err := os.ReadFile(filepath.Join(root, "labels.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	var labels labelsFile
	if err := yaml.Unmarshal(raw, &labels); err != nil {
		t.Fatal(err)
	}

	cfg := config.Default()
	cfg.Scanners.Secrets.Allowlist = nil
	sec := secrets.NewScanner(cfg)
	sastSc := sast.NewScanner(cfg)

	secRes, err := sec.Scan(context.Background(), root, nil)
	if err != nil {
		t.Fatal(err)
	}
	sastRes, err := sastSc.Scan(context.Background(), root, nil)
	if err != nil {
		t.Fatal(err)
	}

	var all []api.Finding
	all = append(all, secRes.Findings...)
	all = append(all, sastRes.Findings...)

	type key struct{ scanner, rule, file string }
	found := map[key]bool{}
	for _, f := range all {
		found[key{f.Scanner, f.RuleID, filepath.ToSlash(f.Location.File)}] = true
	}

	tp, fn := 0, 0
	expected := map[key]bool{}
	for _, l := range labels.Findings {
		if !l.Expect {
			continue
		}
		k := key{l.Scanner, l.Rule, l.File}
		expected[k] = true
		if found[k] {
			tp++
		} else {
			fn++
			t.Errorf("FN: expected %s/%s in %s", l.Scanner, l.Rule, l.File)
		}
	}

	fp := 0
	for k := range found {
		if filepath.Base(k.file) == "clean.go" || filepath.Base(k.file) == "clean.env" {
			fp++
			t.Errorf("FP: %s/%s in %s", k.scanner, k.rule, k.file)
			continue
		}
		if !expected[k] {
			// Extra findings on labeled positive files still count against precision.
			fp++
			t.Logf("extra finding %s/%s in %s (counts as FP for precision)", k.scanner, k.rule, k.file)
		}
	}

	if tp+fp == 0 {
		t.Fatal("no findings; cannot compute precision")
	}
	prec := float64(tp) / float64(tp+fp)
	rec := float64(tp) / float64(tp+fn)
	t.Logf("corpus precision=%.2f recall=%.2f (tp=%d fp=%d fn=%d)", prec, rec, tp, fp, fn)
	if rec < 1.0 {
		t.Errorf("recall %.2f below 1.0 for labeled positives", rec)
	}
	if prec < 0.5 {
		t.Errorf("precision %.2f below floor 0.50", prec)
	}
}
